-- Generated by http://typexpert.net online CSV to SQL converter






INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('297','PHYS3500','PHYS2500');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('298','PHYS3561','PHYS2561');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('299','PHYS3562','PHYS2561');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('300','PHYS3565','PHYS2561');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('301','PHYS3661','PHYS1411');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('302','PHYS3661','PHYS1412');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('303','PHYS3661','PHYS1421');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('304','PHYS3661','PHYS1422');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('305','PHYS3671','PHYS3661');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('306','PHYS3681','PHYS2671');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('307','PHYS3681','PHYS3661');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('308','ELET3405','ELET2405');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('309','ELET3405','ELET2415');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('310','ELET3430','ELET2410');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('311','ELET3430','ELET2430');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('312','ELET3450','ELET2480');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('313','ELET3460','ELET2460');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('314','ELET3480','ELET2480');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('315','ELET3440','ELET2430');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('316','ELET3440','ELET2450');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('317','ELET3490','ELET3405');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('318','ELET3600','PHYS3671');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('319','ELET3600','PHYS3681');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('320','ELET3611','ELET2420');

