-- Generated by http://typexpert.net online CSV to SQL converter

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('1','Additional Mathematics','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('2','Agricultural Science (Double Award)','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('3','Agricultural Science (Single Award)','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('4','Biology','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('5','Building Technology','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('6','Caribbean History','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('7','Chemistry','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('8','Clothing & Textiles','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('9','Economics','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('10','Electronic Document Preparation & Management','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('11','English A','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('12','English B','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('13','Food & Nutrition','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('14','French','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('15','Geography','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('16','Home Economics Management','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('17','Human & Social Biology','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('18','Information Technology','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('19','Integrated Science','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('20','Mathematics','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('21','Mechanical Engineering Technology','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('22','Music','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('23','Office Administration','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('24','Physical Education & Sport','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('25','Physics','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('26','Principles of Accounts','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('27','Principles of Business','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('28','Religious Education','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('29','Social Studies','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('30','Spanish','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('31','Technical Drawing','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('32','Theatre Arts','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('33','Visual Arts','CSEC');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('34','Accounting Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('35','Accounting Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('36','Agricultural Science Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('37','Agricultural Science Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('38','Applied Mathematics Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('39','Applied Mathematics Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('40','Art and Design Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('41','Art and Design Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('42','Biology Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('43','Biology Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('44','Caribbean Studies','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('45','Chemisty Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('46','Chemisty Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('47','Communication Studies','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('48','Computer Science Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('49','Computer Science Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('50','Digital Media','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('51','Economics Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('52','Economics Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('53','Electrical and Electronic Technology','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('54','Entrepreneurship','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('55','Environmental Science Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('56','Environmental Science Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('57','Food and Nutrition Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('58','Food and Nutrition Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('59','French Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('60','French Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('61','Geography Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('62','Geography Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('63','Geometrical and Mechanical Engineering (GMED)','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('64','History Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('65','History Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('66','Information Technology Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('67','Information Technology Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('68','Law Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('69','Law Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('70','Literatures in English Unti 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('71','Literatures in English Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('72','Management of Business Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('73','Management of Business Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('74','Performing Arts','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('75','Physics Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('76','Physics Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('77','Pure Mathematics Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('78','Pure Mathematics Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('79','Sociology Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('80','Sociology Unit 2','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('81','Spanish Unit 1','CAPE');

INSERT INTO cxc (`id`,`cxc_name`,`type`) VALUES ('82','Spanish Unit 2','CAPE');

