-- Generated by http://typexpert.net online CSV to SQL converter

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('1','COMP1161','COMP1126');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('2','COMP1161','COMP1127');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('4','COMP2010','COMP1210');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('5','COMP2120','COMP1210');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('6','COMP2130','COMP1126');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('7','COMP2130','COMP1127');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('8','COMP2130','COMP1161');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('9','COMP2140','COMP1126');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('10','COMP2140','COMP1127');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('11','COMP2140','COMP1161');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('12','COMP2170','COMP2140');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('13','COMP2190','COMP1126');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('14','COMP2190','COMP1127');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('15','COMP2190','COMP1161');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('16','COMP2201','COMP1210');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('17','COMP2211','COMP1126');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('18','COMP2211','COMP1127');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('19','COMP2211','COMP1161');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('20','COMP2211','COMP1210');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('21','COMP2340','COMP1126');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('22','COMP2340','COMP1127');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('23','COMP2340','COMP1161');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('24','COMP2340','COMP1210');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('25','INFO2100','COMP1210');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('26','INFO2110','COMP1126');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('27','INFO2110','COMP1127');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('28','INFO2110','COMP1161');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('29','INFO2180','COMP1126');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('30','INFO2180','COMP1127');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('31','INFO2180','COMP1161');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('32','COMP3101','COMP2340');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('33','COMP3161','COMP1210');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('34','COMP3191','COMP2190');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('35','COMP3192','COMP3191');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('36','COMP3220','COMP2211');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('37','COMP3220','COMP2201');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('38','COMP3270','INFO2180');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('39','COMP3270','COMP2140');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('40','COMP3652','COMP2211');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('41','COMP3702','COMP2201');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('42','COMP3801','COMP2340');

INSERT INTO prereq (`id`,`c_code`,`prereq_code`) VALUES ('43','COMP3801','COMP2140');

